apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-maw
  namespace: default
  labels:
    app: op-maw
spec:
  selector:
    labels:
      app: op-maw
  template:
    metadata:
      labels:
        app: op-maw
    spec:
      containers:
        - name: op-maw
          image: "${IMAGE}"
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          env:
            - name: RUST_LOG
              value: "info,op_maw=debug"
            - name: CERT_PEM
              value: /certs/
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: op-maw-certs
